version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    ports:
      - "3000:3000"
    networks:
      - custom_network
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./MongoDocker
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb-data:/data/db
    networks:
      - custom_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "100:100"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - custom_network
    depends_on:
      - node-app

networks:
  custom_network:

volumes:
  mongodb-data:

